mod ask;
mod classify;
mod deep;
mod describe;
mod doctor;
mod export;
mod fingerprint;
mod helpers;
mod map;
mod mcp;
mod rm;
mod scan;
mod serve;
mod status;
mod summarize;
mod watch;
mod worker;

pub(crate) use ask::cmd_ask;
pub(crate) use classify::cmd_classify;
pub(crate) use deep::cmd_deep;
pub(crate) use describe::cmd_describe;
pub(crate) use doctor::cmd_doctor;
pub(crate) use export::cmd_export;
pub(crate) use fingerprint::cmd_fingerprint;
pub(crate) use map::cmd_map;
pub(crate) use mcp::cmd_mcp;
pub(crate) use rm::cmd_rm;
pub(crate) use scan::cmd_scan;
pub(crate) use serve::cmd_serve;
pub(crate) use status::cmd_status;
pub(crate) use summarize::cmd_summarize;
pub(crate) use watch::cmd_watch;
pub(crate) use worker::cmd_worker;
