//! Anthropic Contextual Retrieval — shared helper.
//!
//! Implements the technique described at <https://www.anthropic.com/news/contextual-retrieval>:
//! each chunk is given a short "situating blurb" generated by a small LLM that explains
//! where the chunk lives in the overall document. The enriched text
//! `"{blurb}\n\n{chunk}"` is **embedded** while the original `chunk.text` is stored in the DB.
//!
//! This is web-agnostic: the callback receives [`ContextualEvent`] values and the caller
//! translates them into surface-specific events (e.g. `JobEvent` in the web path, or a
//! simple stderr print in the CLI path).
//!
//! Recall improvement per Anthropic's study: **−35% retrieval failures** vs raw embeddings
//! (−49% with reranking). Tradeoff: one sequential LLM call per chunk → ~2–3× slower deep
//! phase. Default: **off** (`[describer] contextual_retrieval = false`).

use indexa_llm::Generator;

// ── Public event type ─────────────────────────────────────────────────────────

/// Events emitted during contextual embedding. The caller decides how to surface them.
pub enum ContextualEvent {
    /// A fragment of the context blurb for a chunk was streamed from the LLM.
    BlurbFragment {
        /// Path of the file being processed.
        path: String,
        /// The streamed fragment.
        fragment: String,
    },
    /// The LLM call for one chunk's context blurb failed (fallback: raw chunk text).
    BlurbFailed {
        /// Path of the file being processed.
        path: String,
        /// Error description.
        error: String,
    },
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Build the document-level context string for contextual retrieval.
///
/// Joins all chunk texts separated by double-newlines and caps at 4 000 characters
/// (the same cap used by the web path in `jobs_exec.rs`). Returns an empty string
/// when no chunks are provided.
///
/// Callers pass this string to [`contextual_embed_texts`] for each file.
pub fn build_doc_context(chunk_texts: &[&str]) -> String {
    let joined = chunk_texts.join("\n\n");
    joined.chars().take(4000).collect()
}

/// Enrich a file's chunk texts with one-sentence situating blurbs.
///
/// For each chunk, a small LLM call produces 1–2 sentences explaining where the chunk fits
/// in the document. The return value is `"{blurb}\n\n{chunk_text}"` per chunk; on a
/// per-chunk LLM error the raw chunk text is used as fallback (never propagates the error).
///
/// `on_event` receives [`ContextualEvent`] values so the caller can log fragments or
/// warnings. Pass a no-op closure when events are not needed.
///
/// `cancelled` — optional shared stop flag (e.g. a Ctrl-C signal). When set to `true`
/// the function returns immediately with the texts produced so far, padding the remainder
/// with the original raw chunk texts. Pass `None` to disable cancellation checks.
pub async fn contextual_embed_texts<F>(
    llm: &dyn Generator,
    doc_context: &str,
    chunk_texts: &[&str],
    cancelled: Option<&std::sync::atomic::AtomicBool>,
    path: &str,
    mut on_event: F,
) -> Vec<String>
where
    F: FnMut(ContextualEvent) + Send,
{
    let mut results: Vec<String> = Vec::with_capacity(chunk_texts.len());

    for &chunk_text in chunk_texts {
        // Honour cancellation between chunks.
        if let Some(flag) = cancelled {
            if flag.load(std::sync::atomic::Ordering::Relaxed) {
                results.push(chunk_text.to_owned());
                continue;
            }
        }

        let prompt = build_blurb_prompt(doc_context, chunk_text);
        let path_clone = path.to_owned();
        let mut blurb = String::new();
        let mut on_frag = |frag: String| {
            on_event(ContextualEvent::BlurbFragment {
                path: path_clone.clone(),
                fragment: frag.clone(),
            });
            blurb.push_str(&frag);
        };

        match llm.generate_stream(&prompt, &mut on_frag).await {
            Ok(_) => {
                let enriched = format!("{}\n\n{}", blurb.trim(), chunk_text);
                results.push(enriched);
            }
            Err(e) => {
                on_event(ContextualEvent::BlurbFailed {
                    path: path.to_owned(),
                    error: format!("{e:#}"),
                });
                // Fallback: embed the original text so retrieval isn't broken.
                results.push(chunk_text.to_owned());
            }
        }
    }

    results
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Build the situating blurb prompt. Single source of truth shared by both the
/// CLI (`deep.rs`) and web (`jobs_exec.rs`) paths — keep it here, call it from both.
///
/// Byte-identical to the prompt previously inlined in `jobs_exec.rs:719-727`.
pub fn build_blurb_prompt(doc_context: &str, chunk_text: &str) -> String {
    format!(
        "<document>\n{doc_context}\n</document>\n\n\
         Here is the chunk we want to situate within the whole document:\n\
         <chunk>\n{chunk_text}\n</chunk>\n\n\
         Give a short succinct context (1-2 sentences) to situate this chunk \
         within the overall document for improved search retrieval. \
         Answer only with the succinct context and nothing else."
    )
}

// ── Deterministic contextual prefix (no LLM) ────────────────────────────────────

/// Max characters of the document-context snippet folded into a chunk's prefix. Keeps the
/// prefix from dwarfing the chunk (and from blowing past a small embedder's context window).
const CONTEXT_PREFIX_DOC_CHARS: usize = 500;

/// Build a deterministic document-context prefix for a chunk — **no LLM call**.
///
/// This is the free, local sibling of the Anthropic-style [`contextual_embed_texts`]: instead of
/// an LLM-generated situating blurb, it prepends cheap, deterministic structural signals — the
/// file path, the section heading (when the parser produced one), and a capped snippet of the
/// document-level context — so the chunk's embedding reflects where it sits in the whole document.
/// Same idea voyage-context-4 bakes into its model, realized locally at zero token cost.
///
/// The returned prefix is meant to be prepended to the chunk's **embed input only**; the original
/// chunk text is what gets stored and hashed (see [`contextual_prefix_texts`]).
pub fn build_context_prefix(rel_path: &str, heading: &str, doc_context: &str) -> String {
    let mut prefix = format!("File: {rel_path}");
    let h = heading.trim();
    if !h.is_empty() {
        prefix.push_str("\nSection: ");
        prefix.push_str(h);
    }
    let ctx = doc_context.trim();
    if !ctx.is_empty() {
        let snippet: String = ctx.chars().take(CONTEXT_PREFIX_DOC_CHARS).collect();
        prefix.push_str("\nDocument context: ");
        prefix.push_str(snippet.trim());
    }
    prefix
}

/// Prepend a deterministic context prefix (see [`build_context_prefix`]) to each chunk's embed
/// text. Returns `"{prefix}\n\n{chunk_text}"` per chunk. `headings[i]` pairs with `chunk_texts[i]`
/// (pass `""` where the parser produced no heading). Never calls an LLM and never touches the
/// stored/hashed chunk text — the caller feeds the result to the embedder only.
pub fn contextual_prefix_texts(
    doc_context: &str,
    headings: &[&str],
    chunk_texts: &[&str],
    rel_path: &str,
) -> Vec<String> {
    chunk_texts
        .iter()
        .enumerate()
        .map(|(i, &chunk)| {
            let heading = headings.get(i).copied().unwrap_or("");
            let prefix = build_context_prefix(rel_path, heading, doc_context);
            format!("{prefix}\n\n{chunk}")
        })
        .collect()
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use anyhow::Result;
    use async_trait::async_trait;

    // ── Stub Generator ────────────────────────────────────────────────────────

    /// Echoes a fixed blurb for every call, streaming two fragments.
    struct EchoLlm {
        blurb: &'static str,
    }

    #[async_trait]
    impl Generator for EchoLlm {
        async fn generate(&self, _prompt: &str) -> Result<String> {
            Ok(self.blurb.to_owned())
        }

        async fn generate_stream(
            &self,
            _prompt: &str,
            on_frag: &mut (dyn FnMut(String) + Send),
        ) -> Result<String> {
            // Simulate streaming two fragments.
            on_frag("half1 ".to_owned());
            on_frag("half2".to_owned());
            Ok("half1 half2".to_string())
        }
    }

    /// Always fails with an error.
    struct FailingLlm;

    #[async_trait]
    impl Generator for FailingLlm {
        async fn generate(&self, _prompt: &str) -> Result<String> {
            anyhow::bail!("simulated failure")
        }

        async fn generate_stream(
            &self,
            _prompt: &str,
            _on_frag: &mut (dyn FnMut(String) + Send),
        ) -> Result<String> {
            anyhow::bail!("simulated failure")
        }
    }

    // ── build_doc_context ─────────────────────────────────────────────────────

    #[test]
    fn build_doc_context_joins_chunks() {
        let texts = vec!["chunk one", "chunk two"];
        let ctx = build_doc_context(&texts);
        assert!(ctx.contains("chunk one"));
        assert!(ctx.contains("chunk two"));
        assert!(ctx.contains("\n\n"));
    }

    #[test]
    fn build_doc_context_caps_at_4000_chars() {
        // Feed 10 chunks of 1000 chars each — should be capped at 4000.
        let long = "x".repeat(1000);
        let texts: Vec<&str> = std::iter::repeat_n(long.as_str(), 10).collect();
        let ctx = build_doc_context(&texts);
        assert!(
            ctx.chars().count() <= 4000,
            "exceeded 4000 chars: {}",
            ctx.len()
        );
    }

    #[test]
    fn build_doc_context_empty_input_returns_empty() {
        assert_eq!(build_doc_context(&[]), "");
    }

    // ── contextual_embed_texts ────────────────────────────────────────────────

    #[tokio::test]
    async fn enriched_text_is_blurb_then_chunk() {
        let llm = EchoLlm {
            blurb: "half1 half2",
        };
        let chunks = ["alpha text", "beta text"];
        let results =
            contextual_embed_texts(&llm, "doc context", &chunks, None, "/a.txt", |_| {}).await;

        assert_eq!(results.len(), 2);
        // Each result must be "{blurb}\n\n{chunk_text}"
        assert!(
            results[0].starts_with("half1 half2"),
            "blurb must be first: {}",
            results[0]
        );
        assert!(
            results[0].ends_with("alpha text"),
            "chunk must be last: {}",
            results[0]
        );
        assert!(
            results[0].contains("\n\nalpha text"),
            "separator must be \\n\\n: {}",
            results[0]
        );
    }

    #[tokio::test]
    async fn failing_llm_falls_back_to_raw_chunk() {
        let llm = FailingLlm;
        let chunks = ["important content"];
        let mut events = Vec::new();
        let results = contextual_embed_texts(&llm, "ctx", &chunks, None, "/f.txt", |e| {
            if let ContextualEvent::BlurbFailed { error, .. } = e {
                events.push(error);
            }
        })
        .await;

        assert_eq!(results.len(), 1);
        // Fallback: the raw chunk text is used, not enriched.
        assert_eq!(results[0], "important content");
        // A BlurbFailed event must have been emitted.
        assert!(!events.is_empty(), "no BlurbFailed event emitted");
    }

    #[tokio::test]
    async fn cancellation_uses_raw_chunk_for_remaining() {
        use std::sync::atomic::AtomicBool;
        let llm = EchoLlm { blurb: "blurb" };
        let flag = AtomicBool::new(true); // already cancelled
        let chunks = ["chunk one", "chunk two"];
        let results =
            contextual_embed_texts(&llm, "ctx", &chunks, Some(&flag), "/c.txt", |_| {}).await;

        assert_eq!(results.len(), 2);
        // All chunks should be raw text when already cancelled.
        assert_eq!(results[0], "chunk one");
        assert_eq!(results[1], "chunk two");
    }

    #[tokio::test]
    async fn empty_chunk_list_returns_empty_vec() {
        let llm = EchoLlm { blurb: "blurb" };
        let results = contextual_embed_texts(&llm, "ctx", &[], None, "/e.txt", |_| {}).await;
        assert!(results.is_empty());
    }

    #[tokio::test]
    async fn fragment_events_are_emitted_per_chunk() {
        let llm = EchoLlm {
            blurb: "half1 half2",
        };
        let chunks = ["c1", "c2"];
        let mut fragment_count = 0usize;
        contextual_embed_texts(&llm, "ctx", &chunks, None, "/p.txt", |e| {
            if let ContextualEvent::BlurbFragment { .. } = e {
                fragment_count += 1;
            }
        })
        .await;

        // EchoLlm emits 2 fragments per chunk × 2 chunks = 4 total.
        assert_eq!(
            fragment_count, 4,
            "expected 4 fragment events, got {fragment_count}"
        );
    }

    // ── build_context_prefix / contextual_prefix_texts (deterministic) ─────────

    #[test]
    fn context_prefix_includes_path_heading_and_doc() {
        let p = build_context_prefix("src/foo.rs", "Bar section", "This is the document opening.");
        assert!(p.contains("File: src/foo.rs"), "{p}");
        assert!(p.contains("Section: Bar section"), "{p}");
        assert!(
            p.contains("Document context: This is the document opening."),
            "{p}"
        );
    }

    #[test]
    fn context_prefix_omits_empty_heading_and_doc() {
        let p = build_context_prefix("a.txt", "", "");
        assert_eq!(p, "File: a.txt");
        assert!(!p.contains("Section:"));
        assert!(!p.contains("Document context:"));
    }

    #[test]
    fn context_prefix_caps_doc_snippet() {
        // Marker char 'y' appears nowhere in "File: a.md\nDocument context: ", so counting it
        // isolates the doc-snippet contribution from the fixed prefix text.
        let long = "y".repeat(2000);
        let p = build_context_prefix("a.md", "", &long);
        let ys = p.chars().filter(|&c| c == 'y').count();
        assert!(ys > 0, "doc snippet should be present");
        assert!(
            ys <= CONTEXT_PREFIX_DOC_CHARS,
            "doc snippet not capped: {ys}"
        );
    }

    #[test]
    fn prefix_texts_prepend_prefix_then_chunk() {
        let chunks = ["alpha body", "beta body"];
        let headings = ["H1", "H2"];
        let out = contextual_prefix_texts("doc ctx", &headings, &chunks, "f.rs");
        assert_eq!(out.len(), 2);
        assert!(out[0].starts_with("File: f.rs"), "{}", out[0]);
        assert!(out[0].contains("Section: H1"));
        assert!(out[0].ends_with("\n\nalpha body"), "{}", out[0]);
        assert!(out[1].contains("Section: H2"));
        assert!(out[1].ends_with("\n\nbeta body"));
    }

    #[test]
    fn prefix_texts_tolerates_missing_headings() {
        let chunks = ["only chunk"];
        // No headings provided → empty heading, no Section line.
        let out = contextual_prefix_texts("", &[], &chunks, "f.rs");
        assert_eq!(out.len(), 1);
        assert_eq!(out[0], "File: f.rs\n\nonly chunk");
    }
}
